# database for kong
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: egs-mar-ket-place
  name: postgres-kong-volume
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql-market-kongdb/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kong-volume-claim
  namespace: egs-mar-ket-place
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---


# database for ads
#
---
---
#
# database for auth

# database for parse
---
---
# volume for entities
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-entities-volume-claim
  namespace: egs-mar-ket-place
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
# volume for products
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-product-volume-claim
  namespace: egs-mar-ket-place
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn

# database for sales
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-sales-volume
  namespace: egs-mar-ket-place
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql-market-sales/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-sales-volume-claim
  namespace: egs-mar-ket-place
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
